services:
  postgres:
    env_file:
      - ${APP_ENV_FILE:-.env.local}
    ports:
      - "${POSTGRES_BIND_HOST:-127.0.0.1}:${POSTGRES_EXTERNAL_PORT:-3637}:${POSTGRES_INTERNAL_PORT:-5432}"

  web:
    env_file:
      - ${APP_ENV_FILE:-.env.local}
    build:
      target: development
    command:
      - uvicorn
      - app.server.controller:create_app
      - --factory
      - --reload
      - --host
      - 0.0.0.0
      - --port
      - ${WEB_INTERNAL_PORT:-8000}
    ports:
      - "${WEB_BIND_HOST:-127.0.0.1}:${WEB_EXTERNAL_PORT:-3636}:${WEB_INTERNAL_PORT:-8000}"
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./cordis:/app/cordis

  worker:
    env_file:
      - ${APP_ENV_FILE:-.env.local}
    build:
      target: development
    volumes:
      - ./app:/app/app
      - ./src:/app/src
      - ./cordis:/app/cordis
